# Generated by Django 5.1.6 on 2025-02-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_feedback_comment_count_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
    ]
