# Generated by Django 5.1.6 on 2025-02-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_alter_comment_options_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback_app.board'),
        ),
    ]
